---
- name: Install the selinux python module
  package: name={{ item }} state=present
  with_items:
    - libselinux-python
    - libsemanage-python
  tags:
    - libertempo
    - libertempo-selinux

- name: "Set up context workdir"
  sefcontext:
    target: "{{ libertempo_webroot }}(/.*)?"
    setype: httpd_sys_rw_content_t
  tags:
    - libertempo
    - libertempo-selinux

#- name: "Allow {{ web_user }} to use port 12201"
#  seport:
#    ports: 12201
#    proto: tcp
#    setype: http_port_t
#    state: present

- name: Toggles required SElinux booleans
  seboolean:
    name: "{{ item }}"
    persistent: yes
    state: yes
  with_items:
    - httpd_can_network_connect
    - httpd_can_network_connect_db
    - httpd_read_user_content
    - httpd_execmem
  tags:
    - libertempo
    - libertempo-selinux

- name: Restore context on webroot
  command: "restorecon -R -v {{ libertempo_webroot }}"
  tags:
    - libertempo
    - libertempo-selinux
